### PR TITLE
Correct faulty `isPart` logic and resulting value

### PR DESCRIPTION
**Pull request by le717**
This PR corrects the faulty `isPart` logic as pointed out by https://github.com/le717/LDR-Importer/issues/40#issuecomment-31279788 which has probably existed since David Pluntze wrote the script. It also ~~cleans up `locatePart()` (formerly `locate()`) and~~ simplifies the code around reading a file.

The problem (which I expected) is linked parts is now broken due to the corrected logic. Previously, `isPart` was true only when reading the base .ldr model. When parts, subparts, and primitives (basically, everything except the .ldr model) were located via `locate()`, `isPart` was automatically `False` even if it was a top-level part (or `True`). Now that the logic is corrected, linked parts is broken.

~~Another thing I noticed was `locatePart()` checked for a file twice: once using exact case checking and another when only the part filename was converted to lowercase. I do not know why this was done (I think to resolve some issue with Linux compatibility), but I am unsure why that would even be a problem.
~~

This PR is marked as do not merge for 2 reasons:
* @Tribex From the best I can find in `git blame` you added the double patch checking. Do you remember why (if not, that’s fine) and can you check if this path (which removes the double check) still works on Linux?
* @geertdaelemans I am unable to find what needs to be changed in linked bricks to make it correctly work with the corrected `isPart` logic. Could you pull this branch onto your fork (there are lots of beginner-level guides on how to do that), take a look on fixing it and submit a PR back into this branch? I shouldn’t be editing this anymore (except in case if `locatePart()` needs to be fixed), so it should merge in cleanly.

### CODE REVIEW

**Comment by Tribex** [comment]
@le717 I'll test your changes today, need to reinstall ldraw.

As for the double-path-checking, I think I added to deal with Linux filesystem case-sensitivity and some inconsistencies in the location of certain LDR files, but I don't really remember anything else.

:)

**Comment by geertdaelemans** [comment]
I go crazy!
Previously I tested my code by just installing the py-source again. Now, it seems that I need to refer to the zip-file instead. But sometimes it just ignores my changes. And I get completely lost.
How do you guys test your changes?

**Comment by Tribex** [comment]
@geertdaelemans Use `git pull upstream fix-is-subpart` (Then `git checkout fix-is-subpart`) ?

Are you using git from the command line?

**Comment by geertdaelemans** [comment]
Yes, I am using the command line. What is meant by upstream?

**Comment by le717** [comment]
> Yes, the double-case check is needed. 

Alright, thanks for checking. Will revert and better document it, though I wonder: would having only the second case (`partName.lower()`) work too?

> Additionally, many parts fail to import due to the backslash in the pathnames not being converted to the platform-specific path separator.

Oh snap, I forgot about that! I checked the files that were passes before I removed that line, but I must have missed the `s/` and other folders. :\

> How do you guys test your changes?

I do it like this:
* Clone the repo or download the zip (whichever, just get the code)
* Open the Blender addons location in Explorer (`%AppData%\Blender Foundation\Blender\[Version]\scripts\addons\io_scene_ldrimporter`)
* Edit whatever script I need from the repo/zip
* Copy that file to the proper place in the addons, overwriting any existing file
* In the same addons folder, if a folder called `__pycache__` exists, delete it
* Repeat for as many files as I edited
* Open Blender and my changes are loaded

The `__pycache__` deletion is key here. Python generates bytecode of imported modules, and it will load those over the raw source code even if the source is changed. Deleting them will make Python load the revised scripts (and it will proceed to create bytecode of them, hence why we must delete that folder every time).

Do that help you out any?

**Comment by Tribex** [comment]
@le717 Couldn't you just symlink the repository into the addons folder? That simplifies things a great deal, leaving only the deletion of the pycache. Does Windows have symlinking? (Shortcuts?)

**Comment by le717** [comment]
> Yes, I am using the command line. What is meant by upstream?

Upstream is the main repo your fork is based on. So in this case, "upstream" is a generic name for this repo here. However, I've noticed in the latest Git versions (or it may just be GitHub Desktop) `upstream` is replaced by the GitHub username. If `git pull upstream fix-is-subpart` throws an error saying "upstream is not defined", try `git pull le717 fix-is-subpart` instead.

> Couldn't you just symlink the repository into the addons folder? 

Yes, Windows has had symlinks since Vista. They are just a tad complicated to make (the command-line tool doesn't have the best usage) and I'm lazy and haven't done such a time-saving action yet. :P

**Comment by Tribex** [comment]
@le717 Haha, okay. That makes sense. I have had some odd dealings with git lately, I'll have to look into the changes.

Otherwise, most of the features (except part linking) seem to be working fine. :3

**Comment by le717** [comment]
> Otherwise, most of the features (except part linking) seem to be working fine. :3

That's good to hear (since cross-platform support is strangely crazy for this script). Before I revert the code, I'm still wondering if having only the `partName.lower()` case would work (it does not cause any issues on Windows).

**Comment by Tribex** [comment]
@le717 Adding the `partName.lower()` I chose to keep case-sensitivity due to the fact that some people might reference non-lowercase parts in their own models. For example, if you have a custom part in the current directory (`myCustomPart.dat`), and your model references it as such, then `partName.lower()` would fail to find it on a case-sensitive filesystem.

Anyways, off to bed now. Have fun!

**Comment by le717** [comment]
@Tribex OK, that makes sense now. Sorry for making you have to explain it twice, don't know where my head is this morning. :\ Sleep well!

**Comment by Tribex** [comment]
@le717 No problem, I'm not good at explaining things. Good morning!

**Comment by geertdaelemans** [comment]
Oh darn, the guys from support (I work on my company's laptop) have pushed some stuff that completely ruins my AppData directory. The link reported by the Blender add-on itself doesn't even exist. Grrr. ;-/

**Comment by le717** [comment]
@geertdaelemans No idea what can be idea (I don't know what your IT department did). The only other thing I can suggest is installing all the files to `C:\Program Files [(x86)]\Blender Foundation\Blender\VERSION\scripts\addons\io_scene_ldrimporter` and copy/pasting/deleting from there, although that can get annoying fast because of the required admin rights/UAC confirmations...

**Comment by geertdaelemans** [comment]
Hey guys,
I do hope to get coding again in the coming days. It was a bit too busy lately. Sorry.

**Comment by le717** [comment]
@geertdaelemans That's all fine. It is perfectly understood. :)

@Tribex I restored the double-case check (with proper documentation this time), so everything related to that should work again.

**Comment by Tribex** [comment]
@le717 Yay :D

**Comment by le717** [comment]
I just realized I flunked the commit improving top level part detection. I'll fix it first thing in the morning, but if thought I'd give a heads up if you were going to work on linked parts.

(For reference, the `not` in front of `headerParts[0] !=` needs to be removed.)

**Comment by le717** [comment]
@geertdaelemans I was really hoping to get this PR merged for v1.3.0, but since your Blender installation broke and you've presumably been busy, how would does it sound to you if linked bricks is enabled, I'll just feed the linking code the expected value then you can come back afterward, block out the hack, and fix whatever is needed? :)

**Comment by geertdaelemans** [comment]
Please do so. I did spend some time in looking into the issue, messed-up the whole code and have to start over again.

If you can create the proposed hack, that's ok for me. I will eventually come up with a nicer solution (i hope).

Cheers,

Geert

**Comment by le717** [comment]
@geertdaelemans Old logic fudged in b585f041d9688918c4bbda72480b85cbba67fcad. I'll merge this in a short bit.

**Comment by le717** [comment]
Pressed the correct button that time. :sweat_smile:

**Pull request merged**
