### PR TITLE
Add two more paths to Linux path detection

### LINKED ISSUE #113: Missing LDraw Search Path on Linux
Some tutorial out there had me install the ldraw parts in to `~/.ldraw` which isn't currently in the search path of the import script.  I tested this by adding `'~/.ldraw/` to the set of search paths.

This modification didn't work however, and I traced to down to not expanding the `~` character.  So I added the code:

    try:
        FinalLDrawDir = os.path.expanduser(FinalLDrawDir)
    except:
        pass

around line 1046.  Then it worked!

### PR DESCRIPTION
**Pull request by le717**
Also remove a strange path I cannot find the origin for.

Confirmed to fix #113.

### CODE REVIEW

**Comment by Tribex** [comment]
@le717 `/opt/ldraw` would exist in the case that the user installed ldraw as a system-wide package which does not integrate with the rest of the system.
(Which ought to be the case, but I'm not sure if anyone does it.)

**Comment by le717** [comment]
@Tribex I did not know that. Thanks. Do you recommend keeping the path in the search path or no?

**Comment by Tribex** [comment]
@le717 We could probably leave it out until someone opens an issue saying they installed LDraw in /opt/ldraw and LDCad didn't pick it up. :)

**Comment by le717** [comment]
I can't tell if you're being sarcastic or not. :P I'll leave it then. :)

**Comment by Tribex** [comment]
Oops sorry. I wasn't being sarcastic. My bad. If I'm being sarcastic there will be a /s tag at the end. :smile:

**Pull request merged**
